name: BACnet Hub
version: "0.1.0"
slug: bacnet-hub
description: Enables seamless integration between Home Assistant and BACnet/IP.
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: true
hassio_api: false
homeassistant_api: true
hassio_role: default
init: false
map:
  - config:rw
options:
  ha_url: "ws://supervisor/core/websocket"   # Standard: Supervisor-Proxy
  long_lived_token: ""                       # Fallback (leer lassen, wenn Supervisor-Token klappt)
  bacpypes_log_level: "info"
schema:
  ha_url: str
  long_lived_token: str
  bacpypes_log_level: list(debug|info|warning|error)?
