name: BACnet Hub
version: "0.1.0"
slug: bacnet-hub
description: Publiziert Home Assistant Entitäten als BACnet/IP-Objekte (WebSocket only)
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: true
hassio_api: true
homeassistant_api: true
hassio_role: admin
init: false
map:
  - config:rw
options:
  ha_url: "ws://supervisor/core/websocket"   # Standard: Supervisor-Proxy
  long_lived_token: ""                       # Fallback (leer lassen, wenn Supervisor-Token klappt)
  bacpypes_log_level: "info"
schema:
  ha_url: str
  long_lived_token: str
  bacpypes_log_level: list(info|debug|warning)?
