name: BACnet Hub
version: "0.1.0"
slug: bacnet-hub
description: Publiziert Home Assistant Entitäten als BACnet/IP-Objekte (WebSocket only)
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
hassio_api: true
homeassistant_api: true
hassio_role: default
host_network: true
options: {}
schema: {}
map:
  - config:rw
